config/routes.rb
Rails.application.routes.draw do
  root 'welcome#series'

  get 'episodios', to: 'welcome#episodios'
  get 'detalle', to: 'welcome#detalle_episodio'
  get 'personaje', to: 'welcome#detalle_personaje'
  get 'personajes', to: 'welcome#personajes'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
require "http"
require 'json'

class WelcomeController < ApplicationController
    
    def series
        @temporadas_bb = 0
        @temporadas_bcs = 0
        response_bb = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Breaking+Bad")
        results_bb = JSON.parse(response_bb.to_str)
        response_bcs = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=Better+Call+Saul")
        results_bcs = JSON.parse(response_bcs.to_str)

        results_bb.each do |bb|
            if bb["season"].to_i > @temporadas_bb
                @temporadas_bb = bb["season"].to_i
            end
        end
        

        results_bcs.each do |bcs|
            if bcs["season"].to_i > @temporadas_bcs
                @temporadas_bcs = bcs["season"].to_i
            end
        end
        
        
    end

    def episodios
        @serie = params[:serie]
        @temporada = params[:temporada]
        @episodios = 0
        if @serie == "Breaking Bad"
            @serie = "Breaking+Bad"
        else
            @serie = "Better+Call+Saul"
        end
        url = "https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series="+@serie
        response = HTTP.get(url)
        results = JSON.parse(response.to_str)
        if @serie == "Breaking+Bad"
            @serie = "Breaking Bad"
        else
            @serie = "Better Call Saul"
        end
        @lista_episodios = {}
        @numero_episodio = {}
        results.each do |r|
            if r["season"] == @temporada && r["series"] == @serie
                @lista_episodios[r["episode_id"].to_s] = (r["title"])
                @numero_episodio[r["episode_id"].to_s] = (r["episode"])
            end
        end    
        
        
    end

    def detalle_episodio
        @capitulo = params[:capitulo]
        @serie = params[:serie]
        url = "https://tarea-1-breaking-bad.herokuapp.com/api/episodes/"+@capitulo
        response = HTTP.get(url)
        results = JSON.parse(response.to_str)
        @personajes = []
        
        @results = results[0]
        @results["characters"].each do |r|
            @personajes.push(r)
        end
        @largo = @personajes.length().to_s
        
        
        
    end

    def detalle_personaje
        @name = params[:name]
        array = @name.split(" ")
        query = array.join("+")
        url = "https://tarea-1-breaking-bad.herokuapp.com/api/characters?name="+query
        response = HTTP.get(url)
        results = JSON.parse(response.to_str)
        @info = results[0]
        @occup = []
        @aparece_en = []
        @bcs_app = []
        @info["occupation"].each do |i|
            @occup.push(i)  
        end  

        @info["appearance"].each do |i|
            @aparece_en.push(i)  
        end  
        @info["better_call_saul_appearance"].each do |i|
            @bcs_app.push(i)  
        end  
        

    end

    def personajes
        if params[:search].blank?  
            redirect_to("/") and return  
        else  
            @nombre = params[:search].to_s
            query = @nombre
            
            if @nombre.match(/\s/)
                array = @nombre.split(" ")
                query = array.join("+")
            end
            url = "https://tarea-1-breaking-bad.herokuapp.com/api/characters?name="+query
            response = HTTP.get(url)
            results = JSON.parse(response.to_str)
            @results = results
            
        end 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="/">Tarea 1</a>
    <%= form_tag(personajes_path, :method => "get",   
      class: 'navbar-form navbar-left') do %>  
    <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Buscar Personaje", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
  <% end %>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/welcome/detalle_episodio.html.erb
<h2 class="headertekst">Detalles capitulo</h2>
<br>
<br>
<table style="width:50%" class="center">
    <tr><th class="text-center">Serie</th><td><%= @results["series"] %></td></tr>
    <tr><th class="text-center">Título</th><td><%= @results["title"] %></td></tr>
    <tr><th class="text-center">Capitulo</th><td><%= @results["episode"] %></td></tr>
    <tr><th class="text-center">Temporada</th><td><%= @results["season"] %></td></tr>
    <tr><th class="text-center">Fecha emision</th><td><%= @results["air_date"] %></td></tr>
    <tr><th rowspan=<%= @personajes.length().to_s %> class="text-center">Personajes</th><td><%= link_to @personajes[0], personaje_path(name: @personajes[0]) %></td></tr>
    <% for i in 1..(@personajes.length()-1) %>
        <tr><td><%= link_to @personajes[i], personaje_path(name: @personajes[i])%></td></tr>
    <%end%>
    
    
 
</table>

app/views/welcome/detalle_personaje.html.erb
<h2 class="headertekst">Detalles Personaje</h2>
<br>
<br>
<img src=<%= @info["img"] %>   alt="Foto del personaje" class="centro">
<br>
<table style="width:50%" class="center">
    <tr><th class="text-center">Nombre</th><td><%= @info["name"] %></td></tr>
    <tr><th class="text-center">ID</th><td><%= @info["char_id"] %></td></tr>
    <tr><th rowspan=<%= @occup.length().to_s %> class="text-center">Ocupación</th><td><%=  @occup[0] %></td></tr>
    <% for i in 1..(@occup.length()-1) %>
        <tr><td><%=  @occup[i]%></td></tr>
    <%end%>
    <tr><th class="text-center">Estado</th><td><%= @info["status"] %></td></tr>
    <tr><th class="text-center">Sobrenombre</th><td><%= @info["nickname"] %></td></tr>
    <tr><th class="text-center">Actor/Actriz</th><td><%= @info["portrayed"] %></td></tr>
    <% if @aparece_en !=[]%>
    <tr><th rowspan=<%= @aparece_en.length().to_s %> class="text-center">Aparece en Breaking Bad en</th><td><%= link_to "Temporada " + @aparece_en[0].to_s, episodios_path(temporada: @aparece_en[0], serie: "Breaking Bad") %></td></tr>
    <% for i in 1..(@aparece_en.length()-1) %>
        <tr><td><%= link_to "Temporada " + @aparece_en[i].to_s, episodios_path(temporada: @aparece_en[i], serie: "Breaking Bad") %></td></tr>
    <%end%>
    <%end%>
    <% if @bcs_app != []%>
    <tr><th rowspan=<%= @bcs_app.length().to_s %> class="text-center">Aparece en Better Call Saul en</th><td><%= link_to "Temporada " + @bcs_app[0].to_s, episodios_path(temporada: @bcs_app[0], serie: "Better Call Saul") %></td></tr>
    <% for i in 1..(@bcs_app.length()-1) %>
        <tr><td><%= link_to "Temporada " + @bcs_app[i].to_s, episodios_path(temporada: @bcs_app[i], serie: "Better Call Saul") %></td></tr>
    <%end%>
    <%end%>
    
    
    
 
</table>


app/views/welcome/episodios.html.erb
<h2 class="headertekst"><%=@serie %></h2>
<br>
<br>
<table style="width:50%" class="center">
  <tr>
    <th rowspan=@lista_episodios.length().to_Str class="text-center"><%= "Temporada "+@temporada %></th>
    <% @lista_episodios.each_pair do |k, v| %>
    <tr><td><%= link_to "Episodio "+@numero_episodio[k].to_s+": "+v, detalle_path(capitulo: k, serie: @serie) %></td></tr>
    <%end%>
  </tr>
  </table>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  El nombre del personaje es <%= @name %>
</p>

app/views/welcome/personajes.html.erb
<h2 class="headertekst">Buscas a...?</h2>
<br>
<br>
<table style="width:50%" class="center">
    <% @results.each do |r| %>
        <tr><td><%= link_to r["name"], personaje_path(name: r["name"])%></td></tr>
    <%end%>
</table>

app/views/welcome/series.html.erb
<h2 class="headertekst">Series y Temporadas</h2>
<br>
<br>
<table style="width:50%" class="center">
  <tr>
    <th rowspan=@temporadas_bb.to_Str class="text-center">Breaking Bad</th>
    <% for i in 1..@temporadas_bb %>
    <tr><td><%= link_to "Temporada " + i.to_s, episodios_path(temporada: i, serie: "Breaking Bad") %></td></tr>
    <%end%>
  </tr>
  <tr>
    <th rowspan=@temporadas_bcs.to_Str class="text-center">Better call Saul</th>
    <% for i in 1..@temporadas_bcs %>
    <tr><td><%= link_to "Temporada " + i.to_s, episodios_path(temporada: i, serie: "Better call Saul") %></td></tr>
    <%end%>
  </tr>
  
</table>

<%= @results %>